# Generated by Django 4.0.5 on 2022-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_curso_profesor_delete_familiar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
