# Generated by Django 4.0.5 on 2022-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_profesor_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
