# Generated by Django 4.0.5 on 2022-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_profesor_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
