# Generated by Django 4.0.5 on 2022-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_curso_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
